### ISSUE TITLE
COMDEX namespace environment variables not being applied

### ISSUE THREAD

**Issue by ourlink** [akash-network/cosmos-omnibus#717]
Using [deploy.cloudmos.io ](https://deploy.cloudmos.io/) we deployed a Comdex instance to Akash. The deployment worked, however, the environment variables we set for the instance to include within the config.toml and app.toml files does not work.

The environment variables we used were
```      
      - COMDEX_API_ENABLE=1
      - COMDEX_P2P_PRIVATE_PEER_IDS=9e1ee53832d330adcaf0f9830e2b4ee1be6b6123
      - COMDEX_P2P_UNCONDITIONAL_PEER_IDS=9e1ee53832d330adcaf0f9830e2b4ee1be6b6123
```
We used the shell to cat both files and the above changes were not included. In addition, we get a forwarded port for 1317 (the API) but the API does not respond.

We have deployed other chains for use as an API instance and they seem to work fine. We are just having issues with the Comdex chain.

You can attempt to use the API here -  http://provider.validatornode.com:32508/cosmos/auth/v1beta1/params

**Comment by ourlink** [comment]
Okay, I understand now. The files do not change it is the ENVIRONMENT VARIABLES that are passed to the docker instance at startup. 

However, I tried all the variations of the following and none worked.
``COMDEX_API_ENABLE=True``
``COMDEX_API_ENABLE=true``
``COMDEX_API_ENABLE=TRUE``

During my testing, I tried different providers to ensure it was not the provider having network issues.

None of these settings enabled the API port 1317 although the port was mapped and presented with a redirect.

Any ideas?

I have pasted my test SDL below
```
---
version: "2.0"
services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.4.4-comdex-v13.4.0
    env:
      - MONIKER=ValidatorNode_Sentry1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/comdex/chain.json
      - STATESYNC_RPC_SERVERS=https://comdex-rpc.polkachu.com:443,https://rpc.comdex.one:443,https://rpc-comdex.goldenratiostaking.net:443
      - STATESYNC_SNAPSHOT_INTERVAL=1000
      - MINIMUM_GAS_PRICES=0.025ucmdx
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
      - COMDEX_API_ENABLE=true
      - COMDEX_P2P_PRIVATE_PEER_IDS=9e1ee53832d330adcaf0f9830e2b4ee1be6b6123
      - COMDEX_P2P_UNCONDITIONAL_PEER_IDS=9e1ee53832d330adcaf0f9830e2b4ee1be6b6123
      - PRUNING=custom
      - PRUNING_KEEP_RECENT=100
      - PRUNING_KEEP_EVERY=0
      - PRUNING_INTERVAL=10
    expose:
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 10Gi
        storage:
          size: 125Gi
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000
#      signedBy:
#        anyOf:
#          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  node:
    dcloud:
      profile: node
      count: 1
```
